pipeline {
    agent any

    stages {
        stage('Setup Infisical') {
            steps {
                script {
                    node {
                        withInfisical(
                            configuration: [
                                infisicalCredentialId: 'Infisical',
                                infisicalEnvironmentSlug: 'prod',
                                infisicalProjectSlug: 'devops',
                                infisicalUrl: 'https://app.infisical.com'
                            ],
                            infisicalSecrets: [
                                infisicalSecret(
                                    includeImports: true,
                                    path: '/',
                                    secretValues: [
                                        [infisicalKey: 'POSTGRESDBLINK'],
                                        [infisicalKey: 'POSTGRESDBUSER'],
                                        [infisicalKey: 'POSTGRESDBPASS'],
                                        [infisicalKey: 'THIS_KEY_MIGHT_NOT_EXIST', isRequired: false]
                                    ]
                                )
                            ]
                        ) {
                            sh "printenv"
                            env.POSTGRESDBLINK = "${env.POSTGRESDBLINK}"
                            env.POSTGRESDBUSER = "${env.POSTGRESDBUSER}"
                            env.POSTGRESDBPASS = "${env.POSTGRESDBPASS}"
                        }
                    }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('ClipperOS') {
                    script {
                        sh 'docker build -t clipperos:latest .'
                    }
                }
            }
        }
    }
}
