pipeline {
    agent any

    stages {
        stage('Setup Infisical') {
            steps {
                script {
                    withInfisical(
                        configuration: [
                            infisicalCredentialId: 'Infisical',
                            infisicalEnvironmentSlug: 'prod',
                            infisicalProjectSlug: 'devops',
                            infisicalUrl: 'https://app.infisical.com'
                        ],
                        infisicalSecrets: [
                            infisicalSecret(
                                includeImports: true,
                                path: '/',
                                secretValues: [
                                    [infisicalKey: 'POSTGRESDBLINK'],
                                    [infisicalKey: 'POSTGRESDBUSER'],
                                    [infisicalKey: 'POSTGRESDBPASS'],
                                    [infisicalKey: 'THIS_KEY_MIGHT_NOT_EXIST', isRequired: false]
                                ]
                            )
                        ]
                    ) {
                        echo "Secrets loaded from Infisical"

                        env.DB_LINK = env.POSTGRESDBLINK
                        env.DB_USER = env.POSTGRESDBUSER
                        env.DB_PASS = env.POSTGRESDBPASS
                    }
                }
            }
        }
        
      stage('Run docker Postgres') {
          steps {
              script {
                  sh 'docker start postgres-db || true'  
                  sh 'docker start pgadmin || true' 
              }
          }
      }
      
        stage('Build Docker Image') {
            steps {
                script {
                    sh 'docker build -t clipperos:latest -f ClipperOS/Dockerfile ClipperOS'
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                script {
                    // Remove container existente, se houver
                    sh 'docker rm -f clipperos_container || true'

                    // Usa as variáveis exportadas globalmente
                    sh """
                        docker run -d \
                            -p 8088:8088 \
                            -e POSTGRESDBLINK="${env.DB_LINK}" \
                            -e POSTGRESDBUSER="${env.DB_USER}" \
                            -e POSTGRESDBPASS="${env.DB_PASS}" \
                            --name clipperos_container \
                            clipperos:latest
                    """
                }
            }
        }
    }
}
